### ISSUE TITLE
Cannot send messages via TopicClient from Azure webjob

### ISSUE THREAD

**Issue by JimiSmith** [Azure/azure-service-bus-dotnet#182]
## Actual Behavior
1. Implement Azure WebJob (not using the WebJobs sdk) to send messages to a topic
2. Message sending fails after 30 seconds with the following error and stacktrace

```
An attempt was made to access a socket in a way forbidden by its access permissions
at Microsoft.Azure.ServiceBus.Amqp.AmqpMessageSender.<OnSendAsync>d__19.MoveNext()
End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.ServiceBus.Core.MessageSender.<>c__DisplayClass9_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__9.MoveNext()
```

## Expected Behavior
1. The message should be sent to the topic without errors

## Versions  
- .NET Version: netcoreapp1.1 referencing a netstandard1.6 dll
- NuGet package version: Microsoft.Azure.ServiceBus - 0.0.2-preview

## Other notes

This code works correctly when running locally, connected to the same Azure Service Bus, it only fails when running as a WebJob on Azure

**Comment by SeanFeldman** [comment]
Out of curiosity, @JimiSmith have you tried with the latest pre-release ([0.0.6-preview](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/))?

**Comment by nemakam** [comment]
@JimiSmith, Since this is not an exception thrown by SERVICEBUS, have you tried the various generic solutions present online/stackoverflow for the same error

**Comment by JimiSmith** [comment]
It looks like the issue is related to a client websocket connection that I have running within the same webjob. This appears to be what is using up all the available outbound ports.
