### ISSUE TITLE
Exceptions that occur during an automatic RenewLock action stops the message pump

### ISSUE THREAD

**Issue by brutaldev** [Azure/azure-service-bus-dotnet#397]
## Actual Behavior
When using `RegisterMessageHandler` and internal exceptions occur during the automatic renew lock operation, the message pump stops and the callback method is no longer invoked, the pump cancellation token is set or the receiver is closed (not sure which, explained below).

## Expected Behavior
Internal exceptions should not stop the message pump, cancel the token or close the receiver connection.

## Versions  
- OS platform and version: Windows 2016
- .NET Version: 4.6.1
- NuGet package version or commit ID: 2.0.0

Whenever an exception occurs during a renew lock, the message pump simply stops. The `exceptionRecievedHandler` picks this up, and then the `handler` on `RegisterMessageHandler` stops being invoked.

The `handler` is wrapped in 
`if (!ct.IsCancellationRequested && !serviceBusClient.Receiver.IsClosedOrClosing)` so it's possible that this exception either cancels the internal `pumpCancellationToken` passed into the callback, or closes the receiver, neither of which is ideal or expected. Going to all logging around that to determine exactly why it stops.

The concurrent call setting is 1 so it's very obvious when this suddenly stops which could also mean that `maxConcurrentCallsSemaphoreSlim` may not be getting released correctly. On a side note, if the `exceptionRecievedHandler` throws an exception on [line 150](https://github.com/Azure/azure-service-bus-dotnet/blob/e1bd055cf22b68eb43ac8ce2d10af8f7eb4e720e/src/Microsoft.Azure.ServiceBus/MessageReceivePump.cs#L150) the `maxConcurrentCallsSemaphoreSlim` is never released (not the case here).

The [call is wrapped by a `TaskExtensionHelper.Schedule`](https://github.com/Azure/azure-service-bus-dotnet/blob/e1bd055cf22b68eb43ac8ce2d10af8f7eb4e720e/src/Microsoft.Azure.ServiceBus/MessageReceivePump.cs#L134) so this might be related to https://github.com/Azure/azure-service-bus-dotnet/issues/186

The following is the stack trace of the exception that is provided to the exception handler:
```
Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:***, TrackingId:***, SystemTracker:***~31, Timestamp:1/1/2018 2:13:03 AM
 at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<OnRenewLockAsync>d__91.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass72_0.<<RenewLockAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<RenewLockAsync>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<RenewLockAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Azure.ServiceBus.MessageReceivePump.<RenewMessageLockTask>d__15.MoveNext()ServiceBusException
```

**Comment by nemakam** [comment]
> Whenever an exception occurs during a renew lock, the message pump simply stops.

We don't take any action on the pump when renew fails. We still need to figure out why the pump stops, but it's not related to renew failing. 

> On a side note, if the exceptionRecievedHandler throws an exception on line 150 the maxConcurrentCallsSemaphoreSlim is never released (not the case here).

`ExceptionReceivedHandler` is called inside try-catch with a `system.Exception` catch. So that case should never happen. 

Just looking at code, I don't see any glaring issues that may lead to this. Will need some additional information from you -
1. Is `ServiceBusDiagnosticSource` enabled for you?
1. Is Auto complete enabled, or do you complete it within the handler?
1. What do you do inside your handler when `if (!ct.IsCancellationRequested && !serviceBusClient.Receiver.IsClosedOrClosing)` condition is not true? Do you throw here? Is it possible that your handler doesn't return? Could you add some logging to ensure both of your handlers return successfully and not get stuck? 
1. Have you found any other exception during this period other than `MessageLockLostException`? Including transient ones like `CommunicationException`?
1. Are you starting new threads inside your handlers? (Either the message handler or the exception handler)?

**Comment by nemakam** [comment]
If nothing looks fishy, its easier to get the traces and look at it. Could you please enable traces for `Microsoft-Azure-ServiceBus` logging and repro the issue?

**Comment by brutaldev** [comment]
@nemakam I'll create a demo app for this because it only happens about once a day in production.

> ExceptionReceivedHandler is called inside try-catch with a system.Exception catch. So that case should never happen.

OK I see this now, I just looked at the method call in the pump and not inside the handler options.

> Is ServiceBusDiagnosticSource enabled for you?

No.

> Is Auto complete enabled, or do you complete it within the handler?

Disabled, messages are completed, abandoned and dead-lettered manually based on the result.

> What do you do inside your handler when if (!ct.IsCancellationRequested && !serviceBusClient.Receiver.IsClosedOrClosing) condition is not true? Do you throw here? Is it possible that your handler doesn't return? Could you add some logging to ensure both of your handlers return successfully and not get stuck?

Nothing at all. Since the token is set it's unlikely any receiver calls will work, and if the reciever is closed or closing there really isn't anything we can do here so all processing is avoided. It's at this point we'll just let the message lapse. You would expect automatic renews to stop here too, but it doesn't and I think that might be related to issue #372

> Have you found any other exception during this period other than MessageLockLostException? Including transient ones like CommunicationException?

Sure, errors are caught by the exception handler when the message handler throws (UserCallback) and also when abandoning fails during shutdowns where the is closed or closing check passes but closing just before the abandon. It's only the automatic renew that stops the pump, every single time without fail which is why I think it will be possible to create a sample app that reproduces this.

> Are you starting new threads inside your handlers? (Either the message handler or the exception handler)?

The code in the various message handlers gets pretty crazy, everything from web calls to parallel loops, database hits etc. Absolutely nothing in the exception handler exception writing to the log, and after a log is written about an internal renew failure, the messages stop.

Leaving this overnight now with some big queues, will check in the morning if there are any renew failures and it stopped again. If not I'll get onto a small sample app to try and replicate.

> If nothing looks fishy, its easier to get the traces and look at it. Could you please enable traces for Microsoft-Azure-ServiceBus logging and repro the issue?

Is there documentation to enable this? Not sure how useful this can be or if it will impact the production system that handles millions of message a day.

**Comment by nemakam** [comment]
@brutaldev 

We are in process of adding documentation for logging. Meanwhile, simplest way to enable ETW would be:
1. Download [PerfView](https://www.microsoft.com/en-us/download/details.aspx?id=28567)
2. Run `PerfView.exe /OnlyProviders=*Microsoft-Azure-ServiceBus Collect` 
3. Stop the collection of traces once you have successful repro.
4. Share the `*.etl` files with us. (Please note, you might have sensitive data like `entityName` and `MessageId` as part of the trace file. But information like `message.Body` or `connectionString` will not be present).


Also, Is there an extended period of time where there are no messages received on that link?

**Comment by brutaldev** [comment]
@nemakam 
OK thanks, I'll do that locally with the sample app.

This happened again at 3 this morning on a single instance service and the pump completely stopped as expected and the queue is up to nearly 500k messages now. The service is still running and there is nothing logged with my checks for the cancellation token or for the check if the receiver is closed so this appears to be internal.

Something that is really odd is that the message handler on this particular service simply drains the queue into an internal `Queue<T>`, this operation simply cannot be taking 5 minutes so it should never be renewing unless the `CompleteAsync` takes forever...

The code looks as simple as this (without all the logging and deal-lettering for exceptions) and still ends up renewing internally.
```
serviceBusClient.Receiver.RegisterMessageHandler(async (message, ct) =>
{
  if (!ct.IsCancellationRequested && !serviceBusClient.Receiver.IsClosedOrClosing)
  {
    processingConcurrentQueueObject.Enqueue(message.Body);
    await serviceBusClient.Receiver.CompleteAsync(message.SystemProperties.LockToken);
  }
  else
  {
    // Log stuff around the token and closed/closing state (doesn't show).
    await serviceBusClient.Receiver.AbandonAsync(message.SystemProperties.LockToken);
  }
},
new MessageHandlerOptions(ExceptionReceivedHandler)
{
  AutoComplete = false,
  MaxAutoRenewDuration = TimeSpan.FromMinutes(5),
  MaxConcurrentCalls = Environment.ProcessorCount
});
```
So with the receiver still open and the cancellation token is not set to cancelled, this means the library is no longer calling the message handler. I'll get onto a sample app now because I really need this fixed.

**Comment by brutaldev** [comment]
@nemakam 
Looking at the logs that lead up to the renew event, things did stop processing for close to five minutes, then the renew error is logged and nothing more after that. Is it possible that the `CompleteAsync` calls gets stuck which causes the renews to fail and ultimately no more messages come through?

```
...
03 Jan 2018 03:07:50.4400 [Information] Starting search index batch of 312 items
03 Jan 2018 03:08:01.5420 [Information] Starting search index batch of 6 items
... No logs
03 Jan 2018 03:12:40.0460 [Error] <ServiceBusMessageQueueError> Error in service bus queue. Action="RenewLock" Endpoint="***.servicebus.windows.net" QueueName="***"
Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:***, TrackingId:***, SystemTracker:***~255|search-indexer, Timestamp:1/3/2018 1:12:38 AM
```

**Comment by brutaldev** [comment]
@nemakam 
So I can reproduce an internal renew lock error with a sample app, just use a very high concurrency value and complete the message 10 seconds before they renew (the renew buffer). They start overlapping and messages get completed at the same time they try to get renewed so all the race conditions trigger a bunch of `MessageLockLostException` for `RenewLock` actions.

However, this does not stop the pump. Based on my previous comment and the investigation into what happened before the renew lock exception occurred, I'm starting to think it's the `CompleteAsync` that gets stuck. With the simple code it's not likely it's race conditions and since it should complete in one second and never renew, it must be completing but not stopping the renew lock timer thread. If the complete doesn't go through correctly, it will eventually trigger the renew, but things have stopped pumping a long time ago already.

I'm at a bit of a loss on what to do now. Since I can't figure out why the library would randomly stop pumping messages and the conditions of reproducing it is so difficult, I'm going to have to resort to detecting the renew error as an indication something might be wrong, combined with checking that the message handler hasn't been called in 4-5 minutes and just restart/reconnect it internally to start the pump up again.

**Comment by nemakam** [comment]
@brutaldev 

1. What is the prefetch count you use on the receiver?
Regarding,
> Is there an extended period of time where there are no messages received on that link?

When this condition occurs, do you know the time gap between receiving the previous message and this message? I want to understand for how long was the receiver idle? (For this question, don't consider renewal as an operation).

> this operation simply cannot be taking 5 minutes so it should never be renewing unless the CompleteAsync takes forever...

This is the scenario I'm trying to hunt down. I found a repro for this. It may very well be not related to your issue. At times, `Complete()` is taking forever on a dead expired link.. 

```csharp
serviceBusClient.Receiver.RegisterMessageHandler(async (message, ct) =>
{
  if (!ct.IsCancellationRequested && !serviceBusClient.Receiver.IsClosedOrClosing)
  {
    processingConcurrentQueueObject.Enqueue(message.Body);
    await serviceBusClient.Receiver.CompleteAsync(message.SystemProperties.LockToken);
  }
  else
  {
    // Log stuff around the token and closed/closing state (doesn't show).
    await serviceBusClient.Receiver.AbandonAsync(message.SystemProperties.LockToken);
  }
},
```

In this code, you have `AbandonAsync()` in else. That will not work since the receiver is already closed and hence abandon will just throw. This is not the exception you are facing, but it still doesn't look right.

**Comment by nemakam** [comment]
Meanwhile, either through our ETW traces, or your own logs, can you try to pinpoint if `CompleteAsync` is THE operation which is actually getting stuck?

**Comment by brutaldev** [comment]
@nemakam 

> What is the prefetch count you use on the receiver?

It's zero, we don't use prefetching.

> When this condition occurs, do you know the time gap between receiving the previous message and this message?

It's seems to be close to 5 minutes after the last "progress" message. There are 2-3 progress messages per second then they suddenly stop, for about five minutes then the renew lock errors appear. If automatic renew was disabled, I suspect it will simply just stop. In my scenario this is not an idle connection, it never stops for any period of time unless it's broken.

Agreed about the code, I just quickly modified the basic handler to give you an idea of what it looks like, the actual code just returns a boolean to the base class. The base class code has every operation wrapped in `IsClosedOrClosing` with a double try/catch as well to dead-letter exceptions from the callback along with property attachments for each failure leading up to the dead-letter. That code sample is greatly simplified but I just wanted to highlight that there is nothing weird going on from an implementation point of view.

> Meanwhile, either through our ETW traces, or your own logs, can you try to pinpoint if CompleteAsync is THE operation which is actually getting stuck?

I cannot pinpoint this, it happens rarely (once or twice a day) in a high volume production cluster with several machines so switching on traces would imply logging onto each machine to do this which is not going to be possible. It could very well be `DeadLetterAsync` or `AbandonAsync` calls, under different exception conditions either of these could also be called and if they get stuck then there will be no log message either and of course the renew error would still occur.

I've implemented the timer check I mentioned earlier so if the messages stop pumping for five minutes then the client is disposed, a new instance created, and the handler registered again. I see logs once or twice a day still about this event, but at least it only stops for five minutes.

**Comment by nemakam** [comment]
Related to https://github.com/Azure/azure-amqp/issues/114

**Comment by brutaldev** [comment]
@naile No idea, we've updated to the latest version but all the fallbacks and client object recreation is still in there, if the client goes quiet for 5 minutes we recreate it so even if it's fixed now we won't really know. We also use net messaging in the connection string as AMPQ (at least in this library) seems quite unstable.
