### ISSUE TITLE
System.Timeout on GetRules (full source and example included)

### ISSUE THREAD

**Issue by Eneuman** [Azure/azure-service-bus-dotnet#455]
## Actual Behavior
1. System throws timeout exception

## Expected Behavior
1. Rules should be returned

## Versions  
- OS platform and version: Windows 10 x64
- .NET Version: 2.0
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus 2.0.0

Description:
I created a new Azure Service Bus and added a topic "MyTopic" with both duplicate detection and partitioning.
I added a new policy named "RootManageSharedAccessKey" with all claiems checked.

When running the following code i receive a timeout exception.
This has worked before.

This is my code:

```
  class Program
  {
    static void Main(string[] args)
    {
      MainAsync().GetAwaiter().GetResult();
    }

    static async Task MainAsync()
    {
      const string ServiceBusConnectionString = "<enter connectionstring without topic path>";
      var subscriptionClient = new SubscriptionClient(ServiceBusConnectionString, "MyTopic", "MyService");
      try
      {
        var existingRules = await subscriptionClient.GetRulesAsync();
      }
      catch (Exception ex)
      {
        Console.WriteLine("Failed!");
        throw;
      }

      Console.WriteLine("Success!");
      Console.ReadKey();
    }

  }

```

Error message:
The operation did not complete within the allocated time 00:00:58.7104133 for object request1.

Source:
Microsoft.Azure.ServiceBus

Stacktrace:
```
   at Microsoft.Azure.ServiceBus.Amqp.AmqpSubscriptionClient.<OnGetRulesAsync>d__28.MoveNext() in D:\azure-messaging-dotnet\src\Microsoft.Azure.ServiceBus\Amqp\AmqpSubscriptionClient.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.SubscriptionClient.<GetRulesAsync>d__54.MoveNext() in D:\azure-messaging-dotnet\src\Microsoft.Azure.ServiceBus\SubscriptionClient.cs:line 507
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceBusTester.Program.<MainAsync>d__1.MoveNext() in c:\users\perbornsjö\source\repos\ServiceBusTester\ServiceBusTester\Program.cs:line 23
```

After making 1 call, i get 2.2 Milljon Server errors..

![image](https://user-images.githubusercontent.com/12099277/39674701-2fb7e6ec-5150-11e8-9692-0e9fca5c2f85.png)

**Comment by nemakam** [comment]
@Eneuman 
This repo is for service-bus client issues. 
I would suggest to open a support ticket on Azure Portal to get help regarding these issues.
