### ISSUE TITLE
Exception on handling messages

### ISSUE THREAD

**Issue by remcoongit** [Azure/azure-service-bus-dotnet#468]
## Actual Behavior
1.  Exception thrown when receiving messages
2. 

The type initializer for 'Microsoft.Azure.ServiceBus.Primitives.ClientInfo' threw an exception.   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<OnReceiveAsync>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass65_0.<<ReceiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<ReceiveAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<ReceiveAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

For version:
Release 3.0.1
Release 3.0.0

Testing works fine but when integrating in our main solution it throws these errors. Are there any dependencies that might be wrong?

**Comment by nemakam** [comment]
Could you provide a sample client initialization code, and also provide details on the runtime environment? Where are you running this? Which OS? Which framework?

**Comment by remcoongit** [comment]
Hi,

Windows Azure Cloud workers. Azure SDK 2.9  OS family 5 (Windows server 2016).

When I run the process locally (Console application) no issues. When I deploy it to the server and the application starts it keeps on throwing this exception.

**Comment by nemakam** [comment]
@remcoongit 
Could you tell me the dotnet framework version running on the server?
.net version? Is it the full version or .net core?

**Comment by nemakam** [comment]
The only change I can think of between the two versions is our nuget package used to ship 2 binaries, one targeting .net standard, and one target .net full framework.
Since 3.0, we have only been releasing .net standard dll

**Comment by SeanFeldman** [comment]
netstandard2.0 is funny covering net461 AFAIK

**Comment by remcoongit** [comment]
Hi,

It's an Azure Cloud worker role OSFamily 5 (Windows Server 2016).

Structure:
=>.NET 4.6.1 application logic (1)
==>.NET Standard Library logic/wrapper  (2)
===> ServiceBus package (3)

So 1 references 2 and 2 references 3. The solution works fine inside a console app. So when 1 is a console app nothing is wrong. When I have the Azure cloud worker project reference 1 and deploy it to the cloud this error occurs.

I'm not sure what MS Azure deploys/runs on their Cloud Worker VM. From what I've read it's also .NET 4.6.1.

**Comment by LimeyJohnson** [comment]
I am experiencing the same exception in Azure Cloud Worker Role 5

Message handler encountered an exception System.TypeInitializationException: The type initializer for 'Microsoft.Azure.ServiceBus.Primitives.ClientInfo' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by nemakam** [comment]
There are couple of solutions on https://github.com/libgit2/libgit2sharp/issues/1521 . Take a look at them.

**Comment by nemakam** [comment]
Let me know if the solutions there doesn't work. This doesn't look like a bug that we introduced.

**Comment by gkhank** [comment]
Hi! 

I have been reading and confirming the dependencies in my config file yet the clientinfo still throwing the same error for me. I tried out solutions that's been presented here aswell  [libgit2/libgit2sharp#1521](https://github.com/libgit2/libgit2sharp/issues/1521)

Is there any viable solution for this error? @nemakam 


The type initializer for 'Microsoft.Azure.ServiceBus.Primitives.ClientInfo' threw an exception.
Stacktrace:
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<OnReceiveAsync>d__87.MoveNext()
