### ISSUE TITLE
ManagementClient CreateQueueAsync and CreateTopicAsync throw FormatException instead of MessagingEntityAlreadyExistsException

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#516]
Repro:

```c#
var client1 = new ManagementClient(connectionString);
	
var task1 = client1.CreateTopicAsync("topic");
var task2 = client1.CreateTopicAsync("topic");
	
await Task.WhenAll(task1, task2);
```

Expected exception: `MessagingEntityAlreadyExistsException`
Actual exception: `FormatException`, "Cannot add value because header 'Authorization' does not support multiple values."

<details><summary>Stacktrace</summary>
<code>
 at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, HeaderStoreItemInfo info, String value)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.<SendHttpRequest>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.<>c__DisplayClass37_0.<<PutEntity>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.<PutEntity>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.<CreateTopicAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UserQuery.<Main>d__0.MoveNext()
</code>
</details>

**Comment by nemakam** [comment]
The issue was due to RetryPolicy. Your method must have run into some issue and retryPolicy kicked in which is trying to re send the same message. Fixed it in the latest commit.
1. Changed default retry policy to None.
2. If retry policy even kicks in, then make sure I clone the request before I try to send it again.

**Comment by nemakam** [comment]
Its fixed in #481

**Comment by SeanFeldman** [comment]
Should the default retry policy be set to None if request is cloned? Sounds like that was the root problem.

**Comment by nemakam** [comment]
I was planning to remove retry policy completely instead.
Lets say you do "CreateTopic", and there was a Timeout exception. The default policy would try to retry creating it, and ends up throwing `MessagingEntityAlreadyExistsException` which is weird since you know the topic didnt exist. 
So I changed the default to `NoRetry`

**Comment by SeanFeldman** [comment]
Then 👍 to remove it.

**Comment by nemakam** [comment]
I'm going to leave default as `NoRetry` and let it be as is.
If someone is just interested in doing say `GetTopic` or something like that, and he knows what he is doing, there will be an option for him

**Comment by SeanFeldman** [comment]
Shells like "what if" 🙂
Would say it's better to leave the retries to that person rather than bake
it into the client that could cause issues.

**Comment by nemakam** [comment]
Done.. Removed RetryPolicy
