### ISSUE TITLE
Question - Thread-safe

### ISSUE THREAD

**Issue by remcoongit** [Azure/azure-service-bus-dotnet#524]
`var receiver = new MessageReceiver(...);

var s = new SemaphoreSlim(10);

while(true) {
s.Wait();
var message = receiver.ReceiveAsync(..);
new Thread(async () => {
..  do stuff ..
await receiver.CompleteAsync(message.SystemProperties.LockToken);
s.Release();
})
.Start();

}
`

Are the CompleteAsync(), ReceiveAsync()  thread-safe? I know there's the messagepump but the overhead is huge and on a slow/small CPU it's too heavy.

**Comment by nemakam** [comment]
Yes. They are thread safe. 
The code you showed is pretty much how the pump is implemented as well.
I'd like to understand deeper into "overhead is huge on a small CPU". What are your requirements?

**Comment by remcoongit** [comment]
Thanks. Then I'm having a problem with the CompleteAsync(token).

I create about 30 MessageReceivers with each max 3 concurrent threads processing messages from one MessageReceiver. The moment I complete the message I get the following:

The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<DisposeMessagesAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<CompleteAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

When adding another SemaphoreSlim(1) to lock the complete operations; no errors. Also it only happens with high amounts of concurrent message-processing.

--- The overhead:

The implementation above vs the MessagePump that's implemented;  I did a performance profile and the CPU usage with the MessagePump implementation was about up to 40% more expensive.
I don't have any proof here anymore as it was a few months back. I'll run the performance profiler again - let me implement the MessagePump again.

**Comment by nemakam** [comment]
Lets separate the issues out. Lets keep this issue for your performance. Give me details about your Complete on the other thread you already started.

**Comment by nemakam** [comment]
Oops.. Didn't realize the issues were raised by different people. My bad...

**Comment by remcoongit** [comment]
Did profiling and will close this ticket. The question was; is it thread-safe; answer yes.
The profiling with the current version of this nuget package shows its faster to use the included MessagePump.
