### ISSUE TITLE
The WebSocket is in an invalid state ('Aborted') for this operation

### ISSUE THREAD

**Issue by ilya-git** [Azure/azure-service-bus-dotnet#558]
## Actual Behavior
1. I run the message loop with `RegisterMessageHandler`
2. In my logs I see sometimes (quite rare, but still) this exception that I log in a handler for unobserved task exception (`TaskScheduler.UnobservedTaskException`).

=== Exception ===
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.WebSockets.WebSocketException: The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocket.ThrowOnInvalidState(WebSocketState state, WebSocketState[] validStates)
   at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocket.ThrowOnInvalidState(WebSocketState state, WebSocketState[] validStates)
   at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()<---

## Expected Behavior
1. Tasks should be observed in a library

## Versions  
- OS platform and version: Windows 10
- .NET Version: 4.6.2
- NuGet package version or commit ID: 3.0.2

**Comment by nemakam** [comment]
@ilya-git - Do you use web sockets with service bus client? 
`TransportType = TransportType.AmqpWebSockets`?

**Comment by ilya-git** [comment]
Yes, I use `AmqpWebSockets`, thought I suppose default is same sockets as well, just another port (not 443).

**Comment by nemakam** [comment]
The default doesn't go through "webSockets", just sockets :)
Wouldn't have received any exception from websocket code.
