### ISSUE TITLE
OperationCanceledException thrown on CloseAsync

### ISSUE THREAD

**Issue by AshishBoobun** [Azure/azure-service-bus-dotnet#622]
## Actual Behavior
1. Calling SubscriptionClient.CloseAsync seems to always throw an OperationCanceledException, as follows:

`System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.MessagePumpTaskAsync() in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\MessageReceivePump.cs:line 64`

Calling `SubscriptionClient.IsClosedOrClosing`  after the `CloseAsync` always returned true in my scenario. Is this a typical race condition scenario where the pumpCancellationToken is successfully checked (ln58 MessageReceivePump) but actual Close happened after the cancellation token check?

## Expected Behavior
1. Should gracefully close underlying MessageReceivePump and MessageReceiver

## Versions  
- OS platform and version: windows 10
- .NET Version: core 2.x
- NuGet package version or commit ID: Nuget version 3.2.0

**Comment by SeanFeldman** [comment]
Could you please share a simple repro as a GitHub repo? Thanks.

**Comment by axisc** [comment]
@AshishBoobun - please reopen when you have a code repro. I'll close this for now.
