### ISSUE TITLE
Facing Timeout with Microsoft.Azure.ServiceBus, working fine with WindowsAzure.ServiceBus package

### ISSUE THREAD

**Issue by tushartyagi** [Azure/azure-service-bus-dotnet#635]
## Actual Behavior
1. Creating new application to use Microsoft.Azure.ServiceBus (3.3.0) causing timeout exception.
2. Samples provide at azure-service-bus also getting timeout if I provide the connection string. 
3. Azure dashboard show incoming requests, but no messages.
4. Changing the code to use WindowsAzure.ServiceBus (5.1.0) works
5. [ServiceBusExplorer](https://github.com/paolosalvatori/ServiceBusExplorer) works (because it also uses the WindowsAzure.ServiceBus package??)

## Expected Behavior
1. Samples should run if I provide the connection strings.
2. I should not get timeout exception.

## Versions  
- OS platform and version: Windows 10, Version 1803, Build 17134.472
- .NET Version: Dotnet Standard 2.1.500
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus (3.3.0) & WindowsAzure.ServiceBus (5.1.0)
- Region: Central India

![image](https://user-images.githubusercontent.com/1630265/51584558-dde66800-1efb-11e9-9ce7-99f250bbb2a9.png)

**Comment by tushartyagi** [comment]
In case the stack trace is required. Using [TopicSubscriptionWithRuleOperationsSample](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample)

```
Microsoft.Azure.ServiceBus.ServiceBusCommunicationException
  HResult=0x80131500
  Message=A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ErrorCode: TimedOut
  Source=Microsoft.Azure.ServiceBus
  StackTrace:
   at Microsoft.Azure.ServiceBus.Amqp.AmqpSubscriptionClient.<OnRemoveRuleAsync>d__27.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.SubscriptionClient.<RemoveRuleAsync>d__51.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TopicSubscriptionWithRuleOperationsSample.Program.<MainAsync>d__12.MoveNext() in D:\home\coding\dotnet\azure-service-bus\samples\DotNet\GettingStarted\Microsoft.Azure.ServiceBus\TopicSubscriptionWithRuleOperationsSample\Program.cs:line 44
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TopicSubscriptionWithRuleOperationsSample.Program.Main(String[] args) in D:\home\coding\dotnet\azure-service-bus\samples\DotNet\GettingStarted\Microsoft.Azure.ServiceBus\TopicSubscriptionWithRuleOperationsSample\Program.cs:line 31

Inner Exception 1:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

**Comment by SeanFeldman** [comment]
> ServiceBusExplorer works (because it also uses the WindowsAzure.ServiceBus package??)

Correct.

Is TCP port 5671 blocked by any chance? If yes, you'll have to switch using WebSockets.
To validate, you could spin up a VM on Azure and run a sample. I suspect your environment is blocking the TCP port used for AMQP by default.

**Comment by tushartyagi** [comment]
Yes! That was the issue. My org had opened port 5672 for AMQP connections. Opening 5671 resolved the issue.

Thank you so much. 

Closing this issue.
