### ISSUE TITLE
MessageSender doesn't recover from lost connection

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#639]
## Actual Behavior

When sending messages (transaction + send-via from message handler as a response to an incoming message) everything works great until there's a connection loss. Once connection is lost, it's re-established. Message receiver for the message handler recovers and picks up messages. But message sender does **not**. Instead, the incoming message is received and whenever a send operation is attempted, it immediately fails. Exception handler logs `ServiceBusException` with the message `The operation was canceled.`

Full stacktrace:

<details><summary>Stacktrace</summary>

```
at Microsoft.Azure.ServiceBus.Core.MessageSender.<OnSendAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at UserQuery.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessageDispatchTask>d__13.MoveNext()
```
</details>
<br>

~~**Additional observation** - when the exception is taking place, despite receiving mode `PeekLock`, message is received immediately after exception w/o waiting for lock duration to expire, increasing `DeliveryCount` until maximum is reached and it's dead-lettered.~~
 
## Expected Behaviour

1. Message sender should recover and not fail upon sending.
1. LockDuration should be respected.

## Steps to reproduce

1. Setup two queues source and destination (`src` and `dst`).
1. Register `src` with Message Handler with `AutoComplete=false` and `MaxConcurrentCalls=1`.
1. Configure a `MessageSender` to send to `dst` using Send-Via.
1. In the Message handler callback 
    1. Within a transaction scope, send a message using `MessageSender` mentioned earlier.
    1. Complete the incoming message.
    1. Complete the transaction scope.
1. Terminate TCP connection using some tool
1. **Immediately** send a message to `src` using a different tool/app **before** test application connection is restored.
1. See message received and send operation fail with the aforementioned exception until number of receives reaches `MaxDeliveryCount` defined on `src`.
    - Notice `LockDuration` of the incoming message is entirely ignored as well.

<details><summary>Repro code</summary>

```
async Task Main()
{
	var connectionString = Environment.GetEnvironmentVariable("AzureServiceBus_ConnectionString");
	var src = "src";
	var dest = "dst";
	
	await Initiate(connectionString, src, dest);

	var connection = new ServiceBusConnection(connectionString);
	var queueClient = new QueueClient(connection, src, ReceiveMode.PeekLock, RetryPolicy.Default);
	var sender = new MessageSender(connection, dest, src);
	var counter = 1;

	queueClient.RegisterMessageHandler(async (message, token) =>
	{
		$"received {message.MessageId}".Dump();

		using (var scope = new TransactionScope(TransactionScopeOption.RequiresNew, TransactionScopeAsyncFlowOption.Enabled))
		{
			await sender.SendAsync(new Message());
			$"sent".Dump();
		
			await queueClient.CompleteAsync(message.SystemProperties.LockToken);
			
			scope.Complete();
		}
	},
	new MessageHandlerOptions(exceptionArgs =>
	{
		exceptionArgs.Dump();
		//$"failuer happened {counter++} times. Exception: {exceptionArgs.Exception.Message}".Dump();
		return Task.CompletedTask;
	})
	{
		AutoComplete = false,
		MaxConcurrentCalls = 1
	});

	Console.WriteLine("Press enter to exit");
	Util.ReadLine();
}

async Task Initiate(string connectionString, string src, string dest)
{
	var client = new ManagementClient(connectionString);

	await Task.WhenAll(execute(src), execute(dest));

	await client.CloseAsync();

	async Task execute(string queueName)
	{
		if (await client.QueueExistsAsync(queueName))
		{
			await client.DeleteQueueAsync(queueName);
		}
		await client.CreateQueueAsync(new QueueDescription(queueName)
		{
			MaxDeliveryCount = 100,
			LockDuration = TimeSpan.FromMinutes(5)
		});
	}
}
```
</details>

[Repro code (LinqPad file)](https://github.com/Azure/azure-service-bus-dotnet/files/2797945/asb.message.sender.doesnt.recover.from.disconnect.linq.txt)

Also, this is **only** happening with using transaction scope. W/o transaction scope `MessageSender` recovers and no failure is happening.

## Versions  

- OS platform and version: Windows 10 64bit
- .NET Version: .NET 4.7.1
- NuGet package version or commit ID: 3.3.0

**Comment by axisc** [comment]
@SeanFeldman thanks for reporting this. Agree this is a bug. We'll investigate this internally.

**Comment by basvanmeer** [comment]
Hi , we are wondering if there is progress on this issue? We have this issue in production environment. We have no alternative other then not use azure service bus.

**Comment by siimv** [comment]
I am experiencing similar problem, although it seems to be related with MessageReceiver. I have two different stacktraces. It occurs after handler is successfully run and it tries to complete the process. I do not send any other messages from the handler.

One:
```
Microsoft.Azure.ServiceBus.ServiceBusException: The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.Transaction.Controller.DeclareAsync()
   at Microsoft.Azure.ServiceBus.Amqp.AmqpTransactionEnlistment.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpTransactionManager.EnlistAsync(Transaction transaction, ServiceBusConnection serviceBusConnection)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.CompleteAsync(IEnumerable`1 lockTokens)
```

And another:
```
Microsoft.Azure.ServiceBus.ServiceBusException: 'sender23' is closed
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.CompleteAsync(IEnumerable`1 lockTokens)
```

**Comment by marcelvwe** [comment]
We do experience the same problem in our production environment. Messages are re-tried until they are moved to the deadletter queue. This issue is preventing us from migrating away from the, I now believe, depricated full framework client.

**Comment by axisc** [comment]
Thanks for sharing the specifics. We're still investigating this, but don't have an ETA for now. Will share one as soon as we have an update.

**Comment by labarilem** [comment]
We're having the same issue in our production environment. Here's an exception sample:

`Microsoft.Azure.ServiceBus.ServiceBusException: 'sender13' is closed
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)`

Once this exception comes up, the message receiver stops working and these exceptions keep bubbling up every time the sender tries to send a message.
We noticed that the sender id (e.g. 'sender13') is the same in all the successive exceptions.

As a workaround, we're going to dispose and re-instantiate message senders when this error comes up. Are there better ways to do it?

**Comment by SeanFeldman** [comment]
You can't workaround other than restarting your service/receiver.

**Comment by martinosk** [comment]
We are also affected by this issue. This is a showstopper for moving away from the legacy Azure Service Bus SDK.

**Comment by martinosk** [comment]
We are also affected by this issue. This is a showstopper for moving away from the legacy SDK. 
Especially the fact that lockduration is not respected gives us a lot of problems because this causes the number of retries to completely explode for us.
It happens much more frequently on our 3 environments that use Azure Service Bus Standard tier (several times per day). In our prod environment that runs Premium, we only see it rarely (maybe once a week).

**Comment by ekjuanrejon** [comment]
I am also experiencing the same issues. We have migrate all our platform to .net core and are using AKS and having the issue. 

This would greatly help.

**Comment by axisc** [comment]
@martinosk, @ekjuanrejon  - could you also share the errors you are seeing on your end? This will help with the investigation.

**Comment by martinosk** [comment]
`
Microsoft.Azure.ServiceBus.ServiceBusException: The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.Transaction.Controller.DeclareAsync()
   at Microsoft.Azure.ServiceBus.Amqp.AmqpTransactionEnlistment.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpTransactionManager.EnlistAsync(Transaction transaction, ServiceBusConnection serviceBusConnection)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at NServiceBus.DelayedRetryExecutor.Retry(IncomingMessage message, TimeSpan delay, TransportTransaction transportTransaction)
   at NServiceBus.RecoverabilityExecutor.DeferMessage(DelayedRetry action, ErrorContext errorContext)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.ProcessMessage(Task`1 receiveTask)","SourceContext":"NServiceBus.Transport.AzureServiceBus.MessagePump"
`

**Comment by ekjuanrejon** [comment]
2019-03-04 13:37:20.342 WARN  NServiceBus.RecoverabilityExecutor Delayed Retry will reschedule message 'ecd2a70f-9e3a-437e-8259-aa060076750a' after a delay of 00:00:10 because of an exception:
Microsoft.Azure.ServiceBus.ServiceBusException: 'sender9' is closed
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.CompleteAsync(IEnumerable`1 lockTokens)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.ProcessMessage(Task`1 receiveTask)
2019-03-04 13:37:20.343 WARN  NServiceBus.Transport.AzureServiceBus.MessagePump Recoverability failed for message with ID d83ec031-25d9-4f33-9476-7ffbfdc30b6e. The message will be retried. Exception details: Microsoft.Azure.ServiceBus.ServiceBusException: 'sender9' is closed
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at NServiceBus.DelayedRetryExecutor.Retry(IncomingMessage message, TimeSpan delay, TransportTransaction transportTransaction)
   at NServiceBus.RecoverabilityExecutor.DeferMessage(DelayedRetry action, ErrorContext errorContext)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.ProcessMessage(Task`1 receiveTask)

**Comment by ekjuanrejon** [comment]
`2019-03-04 13:37:20.342 WARN  NServiceBus.RecoverabilityExecutor Delayed Retry will reschedule message 'ecd2a70f-9e3a-437e-8259-aa060076750a' after a delay of 00:00:10 because of an exception:
Microsoft.Azure.ServiceBus.ServiceBusException: 'sender9' is closed
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.CompleteAsync(IEnumerable`1 lockTokens)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.ProcessMessage(Task`1 receiveTask)
2019-03-04 13:37:20.343 WARN  NServiceBus.Transport.AzureServiceBus.MessagePump Recoverability failed for message with ID d83ec031-25d9-4f33-9476-7ffbfdc30b6e. The message will be retried. Exception details: Microsoft.Azure.ServiceBus.ServiceBusException: 'sender9' is closed
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at NServiceBus.DelayedRetryExecutor.Retry(IncomingMessage message, TimeSpan delay, TransportTransaction transportTransaction)
   at NServiceBus.RecoverabilityExecutor.DeferMessage(DelayedRetry action, ErrorContext errorContext)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.ProcessMessage(Task`1 receiveTask)`

**Comment by ekjuanrejon** [comment]
I get that exception until I restart the AKS pod

**Comment by SeanFeldman** [comment]
Given this is not the entire log, @ekjuanrejon could you share the following:
1. Is message with that ID 'ecd2a70f-9e3a-437e-8259-aa060076750a' retried infinitely until either dead-lettered or process restarted?
1. Invocation of the same message processing is happening earlier than `LockDuration` expires (5 minutes)?

**Comment by ekjuanrejon** [comment]
@SeanFeldman

1: the message does not go the the dead letter queue. It gets stuck on that infinite loop with send closed

2: not sure what you mean. Just using nsb with the default settings

**Comment by SeanFeldman** [comment]
Regarding # 1 - correct. It won't be dead-lettered as `MaxDeliveryCount` is set to `int.MaxValue` (please confirm).
Regarding #2 - the default `LockDuration` on the queue is set to 5 mins (please confirm). Reprocessing, based on the log timestamp, does it happen in **less than 5 mins apart**?

**Comment by SeanFeldman** [comment]
@axisc I might be wrong about this, yet it looks that the repro in the issue description is exactly what needs to be addressed. What @ekjuanrejon @martinosk @labarilem @marcelvwe @siimv @basvanmeer are describing is directly related to that.

**Comment by axisc** [comment]
apologies for the delay in the investigation and fix. We're actively looking into it and having more folks from the team check on this. Please bear with us.

**Comment by SeanFeldman** [comment]
**Update**: updated the original description. The immediate re-delivery of the message is expected as MessageHandler API with user callback abandons any message failing processing in the user callback code. Please disregard that part. The rest of the issue (failing to send and getting into infinite loop, eventually dead-lettering messages, is still up-to-date.

**Comment by basvanmeer** [comment]
Any update on this?

**Comment by primez** [comment]
Hello. We have had the same issue as well. Exception is identical to what was posted above. 
Due to that exception our Azure Application Insights instance was flooded with over 2M exceptions originating from just 20 messages sent over the night.
The only resolution was to disable transactions, but that is non-desired change we had to do.

**Comment by pradeeshgs** [comment]
We are facing the exact issue as well. Messages are replaying multiple times even though the same has been processed successfully or no unhandled exceptions thrown. Also, if any exception occurs the messages were replayed forever. One other thing I noticed was the messages are moved to error queue after approximately 10 hours (when an intentional exception was introduced in message handler) instead of moving to the error queue sooner.  Below are the exceptions:
1) Microsoft.Azure.ServiceBus.ServiceBusException: 'sender16' is closed
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<OnSendAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.DelayedRetryExecutor.<Retry>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RecoverabilityExecutor.<DeferMessage>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<ProcessMessage>d__20.MoveNext() 


2)Microsoft.Azure.ServiceBus.ServiceBusException: The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Amqp.Transaction.Controller.<DeclareAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpTransactionEnlistment.<OnCreateAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpTransactionManager.<EnlistAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<OnSendAsync>d__52.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<OnSendAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DelayedRetryExecutor.<Retry>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RecoverabilityExecutor.<DeferMessage>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<ProcessMessage>d__20.MoveNext()

**Comment by binzywu** [comment]
We have a pending fix for AMQP transaction: https://github.com/Azure/azure-amqp/pull/139

**Comment by axisc** [comment]
Thanks @yvgopal, @nemakam, and @binzywu

**Comment by SeanFeldman** [comment]
[Microsoft.Azure.Amqp 2.4.2](https://www.nuget.org/packages/Microsoft.Azure.Amqp/2.4.2) is out.

**Comment by SeanFeldman** [comment]
The fix was in the underlying library and could be released as a part of the scheduled minor (3.4.0).

**Comment by ekjuanrejon** [comment]
@SeanFeldman will there be a new release of NSB 7?

**Comment by SeanFeldman** [comment]
@ekjuanrejon NServiceBus (core) is not affected. What's affected is the NServiceBus Azure Service Bus _transport_. Once ASB client with updated AMQP library reference is released, yes, the transport will be patched and released as well.

In case you need the fix sooner, you can reference AMQP library version 2.4.2 directly to override the version brought in by the current ASB client.

**Comment by marcelvwe** [comment]
Thank you for the update. We’ll apply a version bump to the AMQP to apply the fix immediately.
